### ISSUE TITLE
Verify compatibility with Spring 2023 release

### ISSUE THREAD

**Issue by Ianvdl** [Ianvdl/patstat-to-postgresql#1]
This depends on either renewing a license for 2023, or for a contributor to confirm compatibility/changes.

**Comment by vlejd** [comment]
I have the Fall 2023 Edition. Change log for Spring 2023 looks like this: 
  
![Screenshot from 2024-01-28 14-22-57](https://github.com/Ianvdl/patstat-to-postgresql/assets/5410394/2d7a294e-33f9-4e1c-850a-58d7ba382249)

Made a PR for the Fall 2023 Edition compatibility: #3

**Comment by Ianvdl** [comment]
Hi vlejd!

Thank you for the contributions, I appreciate it. I'll review everything soon (probably this coming weekend) and then merge it. I'll credit you in the README as well.

Ian

**Comment by Ianvdl** [comment]
I've merged your pull request for Fall 2023. We'll keep the record of the Spring 2023 changes here (thank you for posting them!), but nobody seems to have needed that version yet, so I'm putting those changes on the back burner until it comes up again.
