### ISSUE TITLE
Verify compatibility with Spring 2024 release,

### ISSUE THREAD

**Issue by vlejd** [Ianvdl/patstat-to-postgresql#4]
I got my hands on PATSTAT_Global_2024_Spring and want to confirm it can be successfully loaded. There are no changes in the data and there is no need to do anything. I am adding this issue for completeness. 

![Screenshot from 2024-10-16 12-17-51](https://github.com/user-attachments/assets/2a1b983d-2492-4661-abdd-4b1f82976b0a)

Here is the latest version of the model Logical model diagram. Seems the one in description is outdated (change in TLS803_LEGAL_EVENT_CODE and TLS223_APPLN_DOCUS).

![Screenshot from 2024-10-16 12-20-47](https://github.com/user-attachments/assets/b11124bc-4e7c-436c-99f1-48c013d2cd9f)

**Comment by Ianvdl** [comment]
Hey @vlejd 

Super, thanks for letting me know that the data model is still fine for Spring 2024! I'll swap out the diagram in the description too. 

I'll create another release just to make it easier for everyone using the scripts too.
